### PR TITLE
Add values files for dev,test deployment. update main values file.

### PR DESCRIPTION
**Pull request by esune**
FYI @PatStLouis

### CODE REVIEW

**Comment by PatStLouis** [comment]
@esune can you expand why the openshift route resource was deleted?

**Comment by esune** [comment]
> @esune can you expand why the openshift route resource was deleted?

I will revert - didn't mean to commit that. Was testing route creation in OpenShift and other projects do not define an OCP route, but rather have the ingress create a self-managed one so deleted the explicit route setting.

**Comment by esune** [comment]
File restored, and added missing value files

**Comment by esune** [comment]
Removed route again as it is not needed, thanks @i5okie for finding the issue with the service port

**Comment by PatStLouis** [comment]
Why is the route not needed? @WadeBarnes

**Comment by WadeBarnes** [comment]
> Why is the route not needed? @WadeBarnes

A managed route resource should be auto-generated by OpenShift based on the ingress.

**Review by WadeBarnes — APPROVED** [review]
Looks good to me.  We'll give this a test tomorrow.

**Review by WadeBarnes — APPROVED** [review]

**Pull request merged**
